# Puerto del servidor
server.port=8081

# Nombre del microservicio
spring.application.name=category-service

# Configuracion de H2 Database
spring.datasource.url=jdbc:h2:mem:categorydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Consola de H2 (visible en http://localhost:8081/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configuracion de JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true